import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const packageRoot = resolve(new URL('..', import.meta.url).pathname);
const sourcePath = resolve(packageRoot, '../../catalog/generated/public.json');
const outputPath = resolve(packageRoot, 'src/catalog.ts');
const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const projects = source.products
  .filter((project) => project.url)
  .map((project) => ({
    id: project.id,
    name: project.name,
    url: project.url,
    description: project.description,
    tier: project.tier === 'core' ? 'focus' : project.tier,
    priority: project.priority,
    category: project.category,
    maturity: project.maturity,
    spotlight: project.spotlight,
    pillarId: project.pillarId,
    domains: [new URL(project.url).hostname],
  }));

const serialized = JSON.stringify(projects, null, 2)
  .replace(/"([a-z]+)":/g, '$1:')
  .replace(/: "([^"]*)"/g, ": '$1'")
  .replace(/(\n {4}url: '[^']*')\n/g, '$1,\n')
  .replace(/\n {2}}\n/g, '\n  },\n');
const content = `// Generated by scripts/generate-catalog.mjs. Do not edit by hand.\nimport type { PortfolioProject } from './types';\n\nexport const DEFAULT_PROJECTS: readonly PortfolioProject[] = ${serialized};\n`;
await writeFile(outputPath, content);
console.log(`Generated ${projects.length} projects from ${sourcePath}`);
